// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clustermsg.proto

package iproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CusCmd int32

const (
	CusCmd_None CusCmd = 0
	// raft
	CusCmd_SyncClusterIndex  CusCmd = 1
	CusCmd_SyncSubscribeInfo CusCmd = 2
	CusCmd_SyncNewMsg        CusCmd = 3
	CusCmd_SyncLiveResult    CusCmd = 4
	CusCmd_SyncDeadResult    CusCmd = 5
	// rpc
	CusCmd_RaftApply                 CusCmd = 6
	CusCmd_CollectClusterIndex       CusCmd = 7
	CusCmd_AskIndex                  CusCmd = 8
	CusCmd_AskSubscribedInfo         CusCmd = 9
	CusCmd_AskIncreasedIndex         CusCmd = 10
	CusCmd_ReportSubscribeInfoOffset CusCmd = 11
	CusCmd_ReportNewMsg              CusCmd = 12
	CusCmd_ReportLiveResult          CusCmd = 13
	CusCmd_ReportDeadResult          CusCmd = 14
)

var CusCmd_name = map[int32]string{
	0:  "None",
	1:  "SyncClusterIndex",
	2:  "SyncSubscribeInfo",
	3:  "SyncNewMsg",
	4:  "SyncLiveResult",
	5:  "SyncDeadResult",
	6:  "RaftApply",
	7:  "CollectClusterIndex",
	8:  "AskIndex",
	9:  "AskSubscribedInfo",
	10: "AskIncreasedIndex",
	11: "ReportSubscribeInfoOffset",
	12: "ReportNewMsg",
	13: "ReportLiveResult",
	14: "ReportDeadResult",
}

var CusCmd_value = map[string]int32{
	"None":                      0,
	"SyncClusterIndex":          1,
	"SyncSubscribeInfo":         2,
	"SyncNewMsg":                3,
	"SyncLiveResult":            4,
	"SyncDeadResult":            5,
	"RaftApply":                 6,
	"CollectClusterIndex":       7,
	"AskIndex":                  8,
	"AskSubscribedInfo":         9,
	"AskIncreasedIndex":         10,
	"ReportSubscribeInfoOffset": 11,
	"ReportNewMsg":              12,
	"ReportLiveResult":          13,
	"ReportDeadResult":          14,
}

func (x CusCmd) String() string {
	return proto.EnumName(CusCmd_name, int32(x))
}

func (CusCmd) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{0}
}

// protoc -Iiproto --go_out=plugins=grpc:./iproto ./iproto/clustermsg.proto
// 持久化存储消息包
type StorePack struct {
	// 每条消息有个唯一的索引ID
	Index uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// 如果为空，表示所有的消费者节点；如果存在，则这些节点需要重试。key为消费者唯一识别key,value为重试次数
	Peers map[string]uint32 `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// Pack  gocmd.PostPacket
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// 记录时间戳
	RecordTime           int64    `protobuf:"varint,4,opt,name=recordTime,proto3" json:"recordTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorePack) Reset()         { *m = StorePack{} }
func (m *StorePack) String() string { return proto.CompactTextString(m) }
func (*StorePack) ProtoMessage()    {}
func (*StorePack) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{0}
}

func (m *StorePack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorePack.Unmarshal(m, b)
}
func (m *StorePack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorePack.Marshal(b, m, deterministic)
}
func (m *StorePack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorePack.Merge(m, src)
}
func (m *StorePack) XXX_Size() int {
	return xxx_messageInfo_StorePack.Size(m)
}
func (m *StorePack) XXX_DiscardUnknown() {
	xxx_messageInfo_StorePack.DiscardUnknown(m)
}

var xxx_messageInfo_StorePack proto.InternalMessageInfo

func (m *StorePack) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *StorePack) GetPeers() map[string]uint32 {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *StorePack) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *StorePack) GetRecordTime() int64 {
	if m != nil {
		return m.RecordTime
	}
	return 0
}

// raft协议，集群日志同步入口
type ApplyLogEntry struct {
	Cmd CusCmd `protobuf:"varint,1,opt,name=cmd,proto3,enum=iproto.CusCmd" json:"cmd,omitempty"`
	// 对应message的protobuf数据
	Data                 *any.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyLogEntry) Reset()         { *m = ApplyLogEntry{} }
func (m *ApplyLogEntry) String() string { return proto.CompactTextString(m) }
func (*ApplyLogEntry) ProtoMessage()    {}
func (*ApplyLogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{1}
}

func (m *ApplyLogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyLogEntry.Unmarshal(m, b)
}
func (m *ApplyLogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyLogEntry.Marshal(b, m, deterministic)
}
func (m *ApplyLogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyLogEntry.Merge(m, src)
}
func (m *ApplyLogEntry) XXX_Size() int {
	return xxx_messageInfo_ApplyLogEntry.Size(m)
}
func (m *ApplyLogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyLogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyLogEntry proto.InternalMessageInfo

func (m *ApplyLogEntry) GetCmd() CusCmd {
	if m != nil {
		return m.Cmd
	}
	return CusCmd_None
}

func (m *ApplyLogEntry) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type CommonReply struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonReply) Reset()         { *m = CommonReply{} }
func (m *CommonReply) String() string { return proto.CompactTextString(m) }
func (*CommonReply) ProtoMessage()    {}
func (*CommonReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{2}
}

func (m *CommonReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonReply.Unmarshal(m, b)
}
func (m *CommonReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonReply.Marshal(b, m, deterministic)
}
func (m *CommonReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonReply.Merge(m, src)
}
func (m *CommonReply) XXX_Size() int {
	return xxx_messageInfo_CommonReply.Size(m)
}
func (m *CommonReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonReply.DiscardUnknown(m)
}

var xxx_messageInfo_CommonReply proto.InternalMessageInfo

func (m *CommonReply) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CommonReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type RaftApplyRequest struct {
	Cmd                  CusCmd   `protobuf:"varint,1,opt,name=cmd,proto3,enum=iproto.CusCmd" json:"cmd,omitempty"`
	Data                 *any.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftApplyRequest) Reset()         { *m = RaftApplyRequest{} }
func (m *RaftApplyRequest) String() string { return proto.CompactTextString(m) }
func (*RaftApplyRequest) ProtoMessage()    {}
func (*RaftApplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{3}
}

func (m *RaftApplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftApplyRequest.Unmarshal(m, b)
}
func (m *RaftApplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftApplyRequest.Marshal(b, m, deterministic)
}
func (m *RaftApplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftApplyRequest.Merge(m, src)
}
func (m *RaftApplyRequest) XXX_Size() int {
	return xxx_messageInfo_RaftApplyRequest.Size(m)
}
func (m *RaftApplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftApplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RaftApplyRequest proto.InternalMessageInfo

func (m *RaftApplyRequest) GetCmd() CusCmd {
	if m != nil {
		return m.Cmd
	}
	return CusCmd_None
}

func (m *RaftApplyRequest) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type RaftApplyReply struct {
	Res                  *CommonReply `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RaftApplyReply) Reset()         { *m = RaftApplyReply{} }
func (m *RaftApplyReply) String() string { return proto.CompactTextString(m) }
func (*RaftApplyReply) ProtoMessage()    {}
func (*RaftApplyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{4}
}

func (m *RaftApplyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftApplyReply.Unmarshal(m, b)
}
func (m *RaftApplyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftApplyReply.Marshal(b, m, deterministic)
}
func (m *RaftApplyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftApplyReply.Merge(m, src)
}
func (m *RaftApplyReply) XXX_Size() int {
	return xxx_messageInfo_RaftApplyReply.Size(m)
}
func (m *RaftApplyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftApplyReply.DiscardUnknown(m)
}

var xxx_messageInfo_RaftApplyReply proto.InternalMessageInfo

func (m *RaftApplyReply) GetRes() *CommonReply {
	if m != nil {
		return m.Res
	}
	return nil
}

// *****************************************
type CollectClusterIndexRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectClusterIndexRequest) Reset()         { *m = CollectClusterIndexRequest{} }
func (m *CollectClusterIndexRequest) String() string { return proto.CompactTextString(m) }
func (*CollectClusterIndexRequest) ProtoMessage()    {}
func (*CollectClusterIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{5}
}

func (m *CollectClusterIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectClusterIndexRequest.Unmarshal(m, b)
}
func (m *CollectClusterIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectClusterIndexRequest.Marshal(b, m, deterministic)
}
func (m *CollectClusterIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectClusterIndexRequest.Merge(m, src)
}
func (m *CollectClusterIndexRequest) XXX_Size() int {
	return xxx_messageInfo_CollectClusterIndexRequest.Size(m)
}
func (m *CollectClusterIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectClusterIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectClusterIndexRequest proto.InternalMessageInfo

type CollectClusterIndexReply struct {
	Res                  *CommonReply `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Index                uint64       `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CollectClusterIndexReply) Reset()         { *m = CollectClusterIndexReply{} }
func (m *CollectClusterIndexReply) String() string { return proto.CompactTextString(m) }
func (*CollectClusterIndexReply) ProtoMessage()    {}
func (*CollectClusterIndexReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{6}
}

func (m *CollectClusterIndexReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectClusterIndexReply.Unmarshal(m, b)
}
func (m *CollectClusterIndexReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectClusterIndexReply.Marshal(b, m, deterministic)
}
func (m *CollectClusterIndexReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectClusterIndexReply.Merge(m, src)
}
func (m *CollectClusterIndexReply) XXX_Size() int {
	return xxx_messageInfo_CollectClusterIndexReply.Size(m)
}
func (m *CollectClusterIndexReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectClusterIndexReply.DiscardUnknown(m)
}

var xxx_messageInfo_CollectClusterIndexReply proto.InternalMessageInfo

func (m *CollectClusterIndexReply) GetRes() *CommonReply {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *CollectClusterIndexReply) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type SyncClusterIndexRequest struct {
	Index                uint64   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncClusterIndexRequest) Reset()         { *m = SyncClusterIndexRequest{} }
func (m *SyncClusterIndexRequest) String() string { return proto.CompactTextString(m) }
func (*SyncClusterIndexRequest) ProtoMessage()    {}
func (*SyncClusterIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{7}
}

func (m *SyncClusterIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncClusterIndexRequest.Unmarshal(m, b)
}
func (m *SyncClusterIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncClusterIndexRequest.Marshal(b, m, deterministic)
}
func (m *SyncClusterIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncClusterIndexRequest.Merge(m, src)
}
func (m *SyncClusterIndexRequest) XXX_Size() int {
	return xxx_messageInfo_SyncClusterIndexRequest.Size(m)
}
func (m *SyncClusterIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncClusterIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncClusterIndexRequest proto.InternalMessageInfo

func (m *SyncClusterIndexRequest) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type SyncClusterIndexReply struct {
	Res                  *CommonReply `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SyncClusterIndexReply) Reset()         { *m = SyncClusterIndexReply{} }
func (m *SyncClusterIndexReply) String() string { return proto.CompactTextString(m) }
func (*SyncClusterIndexReply) ProtoMessage()    {}
func (*SyncClusterIndexReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{8}
}

func (m *SyncClusterIndexReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncClusterIndexReply.Unmarshal(m, b)
}
func (m *SyncClusterIndexReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncClusterIndexReply.Marshal(b, m, deterministic)
}
func (m *SyncClusterIndexReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncClusterIndexReply.Merge(m, src)
}
func (m *SyncClusterIndexReply) XXX_Size() int {
	return xxx_messageInfo_SyncClusterIndexReply.Size(m)
}
func (m *SyncClusterIndexReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncClusterIndexReply.DiscardUnknown(m)
}

var xxx_messageInfo_SyncClusterIndexReply proto.InternalMessageInfo

func (m *SyncClusterIndexReply) GetRes() *CommonReply {
	if m != nil {
		return m.Res
	}
	return nil
}

type SyncSubscribeInfoRequest struct {
	Data                 map[uint32]uint32 `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SyncSubscribeInfoRequest) Reset()         { *m = SyncSubscribeInfoRequest{} }
func (m *SyncSubscribeInfoRequest) String() string { return proto.CompactTextString(m) }
func (*SyncSubscribeInfoRequest) ProtoMessage()    {}
func (*SyncSubscribeInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{9}
}

func (m *SyncSubscribeInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncSubscribeInfoRequest.Unmarshal(m, b)
}
func (m *SyncSubscribeInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncSubscribeInfoRequest.Marshal(b, m, deterministic)
}
func (m *SyncSubscribeInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncSubscribeInfoRequest.Merge(m, src)
}
func (m *SyncSubscribeInfoRequest) XXX_Size() int {
	return xxx_messageInfo_SyncSubscribeInfoRequest.Size(m)
}
func (m *SyncSubscribeInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncSubscribeInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncSubscribeInfoRequest proto.InternalMessageInfo

func (m *SyncSubscribeInfoRequest) GetData() map[uint32]uint32 {
	if m != nil {
		return m.Data
	}
	return nil
}

type SyncSubscribeInfoReply struct {
	Res                  *CommonReply `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SyncSubscribeInfoReply) Reset()         { *m = SyncSubscribeInfoReply{} }
func (m *SyncSubscribeInfoReply) String() string { return proto.CompactTextString(m) }
func (*SyncSubscribeInfoReply) ProtoMessage()    {}
func (*SyncSubscribeInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{10}
}

func (m *SyncSubscribeInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncSubscribeInfoReply.Unmarshal(m, b)
}
func (m *SyncSubscribeInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncSubscribeInfoReply.Marshal(b, m, deterministic)
}
func (m *SyncSubscribeInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncSubscribeInfoReply.Merge(m, src)
}
func (m *SyncSubscribeInfoReply) XXX_Size() int {
	return xxx_messageInfo_SyncSubscribeInfoReply.Size(m)
}
func (m *SyncSubscribeInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncSubscribeInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_SyncSubscribeInfoReply proto.InternalMessageInfo

func (m *SyncSubscribeInfoReply) GetRes() *CommonReply {
	if m != nil {
		return m.Res
	}
	return nil
}

type SyncSubscribeInfoOffsetRequest struct {
	//    true:订阅，false:取消订阅
	Action bool `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"`
	// 要订阅/取消订阅的是协议ID（cmdid）
	Ids []uint32 `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	// 消费者唯一识别字符串key
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncSubscribeInfoOffsetRequest) Reset()         { *m = SyncSubscribeInfoOffsetRequest{} }
func (m *SyncSubscribeInfoOffsetRequest) String() string { return proto.CompactTextString(m) }
func (*SyncSubscribeInfoOffsetRequest) ProtoMessage()    {}
func (*SyncSubscribeInfoOffsetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{11}
}

func (m *SyncSubscribeInfoOffsetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncSubscribeInfoOffsetRequest.Unmarshal(m, b)
}
func (m *SyncSubscribeInfoOffsetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncSubscribeInfoOffsetRequest.Marshal(b, m, deterministic)
}
func (m *SyncSubscribeInfoOffsetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncSubscribeInfoOffsetRequest.Merge(m, src)
}
func (m *SyncSubscribeInfoOffsetRequest) XXX_Size() int {
	return xxx_messageInfo_SyncSubscribeInfoOffsetRequest.Size(m)
}
func (m *SyncSubscribeInfoOffsetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncSubscribeInfoOffsetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncSubscribeInfoOffsetRequest proto.InternalMessageInfo

func (m *SyncSubscribeInfoOffsetRequest) GetAction() bool {
	if m != nil {
		return m.Action
	}
	return false
}

func (m *SyncSubscribeInfoOffsetRequest) GetIds() []uint32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *SyncSubscribeInfoOffsetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type SyncSubscribeInfoOffsetReply struct {
	Res                  *CommonReply `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SyncSubscribeInfoOffsetReply) Reset()         { *m = SyncSubscribeInfoOffsetReply{} }
func (m *SyncSubscribeInfoOffsetReply) String() string { return proto.CompactTextString(m) }
func (*SyncSubscribeInfoOffsetReply) ProtoMessage()    {}
func (*SyncSubscribeInfoOffsetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{12}
}

func (m *SyncSubscribeInfoOffsetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncSubscribeInfoOffsetReply.Unmarshal(m, b)
}
func (m *SyncSubscribeInfoOffsetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncSubscribeInfoOffsetReply.Marshal(b, m, deterministic)
}
func (m *SyncSubscribeInfoOffsetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncSubscribeInfoOffsetReply.Merge(m, src)
}
func (m *SyncSubscribeInfoOffsetReply) XXX_Size() int {
	return xxx_messageInfo_SyncSubscribeInfoOffsetReply.Size(m)
}
func (m *SyncSubscribeInfoOffsetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncSubscribeInfoOffsetReply.DiscardUnknown(m)
}

var xxx_messageInfo_SyncSubscribeInfoOffsetReply proto.InternalMessageInfo

func (m *SyncSubscribeInfoOffsetReply) GetRes() *CommonReply {
	if m != nil {
		return m.Res
	}
	return nil
}

// 获取当前集群的索引
type AskIndexRequest struct {
	Index                uint64   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AskIndexRequest) Reset()         { *m = AskIndexRequest{} }
func (m *AskIndexRequest) String() string { return proto.CompactTextString(m) }
func (*AskIndexRequest) ProtoMessage()    {}
func (*AskIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{13}
}

func (m *AskIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskIndexRequest.Unmarshal(m, b)
}
func (m *AskIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskIndexRequest.Marshal(b, m, deterministic)
}
func (m *AskIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskIndexRequest.Merge(m, src)
}
func (m *AskIndexRequest) XXX_Size() int {
	return xxx_messageInfo_AskIndexRequest.Size(m)
}
func (m *AskIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AskIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AskIndexRequest proto.InternalMessageInfo

func (m *AskIndexRequest) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type AskIndexReply struct {
	Res                  *CommonReply `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Index                uint64       `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AskIndexReply) Reset()         { *m = AskIndexReply{} }
func (m *AskIndexReply) String() string { return proto.CompactTextString(m) }
func (*AskIndexReply) ProtoMessage()    {}
func (*AskIndexReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{14}
}

func (m *AskIndexReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskIndexReply.Unmarshal(m, b)
}
func (m *AskIndexReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskIndexReply.Marshal(b, m, deterministic)
}
func (m *AskIndexReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskIndexReply.Merge(m, src)
}
func (m *AskIndexReply) XXX_Size() int {
	return xxx_messageInfo_AskIndexReply.Size(m)
}
func (m *AskIndexReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AskIndexReply.DiscardUnknown(m)
}

var xxx_messageInfo_AskIndexReply proto.InternalMessageInfo

func (m *AskIndexReply) GetRes() *CommonReply {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *AskIndexReply) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

// 获取集群内已订阅信息表
type AskSubscribedInfoRequest struct {
	// 带上已有的订阅信息
	Data map[uint32]uint32 `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// true:leader向follow请求，false:follow向leader请求
	Bro                  bool     `protobuf:"varint,2,opt,name=bro,proto3" json:"bro,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AskSubscribedInfoRequest) Reset()         { *m = AskSubscribedInfoRequest{} }
func (m *AskSubscribedInfoRequest) String() string { return proto.CompactTextString(m) }
func (*AskSubscribedInfoRequest) ProtoMessage()    {}
func (*AskSubscribedInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{15}
}

func (m *AskSubscribedInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskSubscribedInfoRequest.Unmarshal(m, b)
}
func (m *AskSubscribedInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskSubscribedInfoRequest.Marshal(b, m, deterministic)
}
func (m *AskSubscribedInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskSubscribedInfoRequest.Merge(m, src)
}
func (m *AskSubscribedInfoRequest) XXX_Size() int {
	return xxx_messageInfo_AskSubscribedInfoRequest.Size(m)
}
func (m *AskSubscribedInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AskSubscribedInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AskSubscribedInfoRequest proto.InternalMessageInfo

func (m *AskSubscribedInfoRequest) GetData() map[uint32]uint32 {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AskSubscribedInfoRequest) GetBro() bool {
	if m != nil {
		return m.Bro
	}
	return false
}

type AskSubscribedInfoReply struct {
	Res *CommonReply `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	// 返回别人的
	Data                 map[uint32]uint32 `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AskSubscribedInfoReply) Reset()         { *m = AskSubscribedInfoReply{} }
func (m *AskSubscribedInfoReply) String() string { return proto.CompactTextString(m) }
func (*AskSubscribedInfoReply) ProtoMessage()    {}
func (*AskSubscribedInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{16}
}

func (m *AskSubscribedInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskSubscribedInfoReply.Unmarshal(m, b)
}
func (m *AskSubscribedInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskSubscribedInfoReply.Marshal(b, m, deterministic)
}
func (m *AskSubscribedInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskSubscribedInfoReply.Merge(m, src)
}
func (m *AskSubscribedInfoReply) XXX_Size() int {
	return xxx_messageInfo_AskSubscribedInfoReply.Size(m)
}
func (m *AskSubscribedInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AskSubscribedInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_AskSubscribedInfoReply proto.InternalMessageInfo

func (m *AskSubscribedInfoReply) GetRes() *CommonReply {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *AskSubscribedInfoReply) GetData() map[uint32]uint32 {
	if m != nil {
		return m.Data
	}
	return nil
}

// 获取集群自增后的索引值
type AskIncreasedIndexRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AskIncreasedIndexRequest) Reset()         { *m = AskIncreasedIndexRequest{} }
func (m *AskIncreasedIndexRequest) String() string { return proto.CompactTextString(m) }
func (*AskIncreasedIndexRequest) ProtoMessage()    {}
func (*AskIncreasedIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{17}
}

func (m *AskIncreasedIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskIncreasedIndexRequest.Unmarshal(m, b)
}
func (m *AskIncreasedIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskIncreasedIndexRequest.Marshal(b, m, deterministic)
}
func (m *AskIncreasedIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskIncreasedIndexRequest.Merge(m, src)
}
func (m *AskIncreasedIndexRequest) XXX_Size() int {
	return xxx_messageInfo_AskIncreasedIndexRequest.Size(m)
}
func (m *AskIncreasedIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AskIncreasedIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AskIncreasedIndexRequest proto.InternalMessageInfo

type AskIncreasedIndexReply struct {
	Res                  *CommonReply `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Index                uint64       `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AskIncreasedIndexReply) Reset()         { *m = AskIncreasedIndexReply{} }
func (m *AskIncreasedIndexReply) String() string { return proto.CompactTextString(m) }
func (*AskIncreasedIndexReply) ProtoMessage()    {}
func (*AskIncreasedIndexReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{18}
}

func (m *AskIncreasedIndexReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskIncreasedIndexReply.Unmarshal(m, b)
}
func (m *AskIncreasedIndexReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskIncreasedIndexReply.Marshal(b, m, deterministic)
}
func (m *AskIncreasedIndexReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskIncreasedIndexReply.Merge(m, src)
}
func (m *AskIncreasedIndexReply) XXX_Size() int {
	return xxx_messageInfo_AskIncreasedIndexReply.Size(m)
}
func (m *AskIncreasedIndexReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AskIncreasedIndexReply.DiscardUnknown(m)
}

var xxx_messageInfo_AskIncreasedIndexReply proto.InternalMessageInfo

func (m *AskIncreasedIndexReply) GetRes() *CommonReply {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *AskIncreasedIndexReply) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

// 新消息请求，同步和上报使用同一个结构体
type NewMsgRequest struct {
	Data                 []*StorePack `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NewMsgRequest) Reset()         { *m = NewMsgRequest{} }
func (m *NewMsgRequest) String() string { return proto.CompactTextString(m) }
func (*NewMsgRequest) ProtoMessage()    {}
func (*NewMsgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{19}
}

func (m *NewMsgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMsgRequest.Unmarshal(m, b)
}
func (m *NewMsgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMsgRequest.Marshal(b, m, deterministic)
}
func (m *NewMsgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMsgRequest.Merge(m, src)
}
func (m *NewMsgRequest) XXX_Size() int {
	return xxx_messageInfo_NewMsgRequest.Size(m)
}
func (m *NewMsgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMsgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewMsgRequest proto.InternalMessageInfo

func (m *NewMsgRequest) GetData() []*StorePack {
	if m != nil {
		return m.Data
	}
	return nil
}

type NewMsgReply struct {
	Res                  *CommonReply `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NewMsgReply) Reset()         { *m = NewMsgReply{} }
func (m *NewMsgReply) String() string { return proto.CompactTextString(m) }
func (*NewMsgReply) ProtoMessage()    {}
func (*NewMsgReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{20}
}

func (m *NewMsgReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMsgReply.Unmarshal(m, b)
}
func (m *NewMsgReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMsgReply.Marshal(b, m, deterministic)
}
func (m *NewMsgReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMsgReply.Merge(m, src)
}
func (m *NewMsgReply) XXX_Size() int {
	return xxx_messageInfo_NewMsgReply.Size(m)
}
func (m *NewMsgReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMsgReply.DiscardUnknown(m)
}

var xxx_messageInfo_NewMsgReply proto.InternalMessageInfo

func (m *NewMsgReply) GetRes() *CommonReply {
	if m != nil {
		return m.Res
	}
	return nil
}

// 新消息派发结果，同步和上报使用同一个结构体
type LiveResultRequest struct {
	Success              []uint64 `protobuf:"varint,1,rep,packed,name=success,proto3" json:"success,omitempty"`
	Fail                 []uint64 `protobuf:"varint,2,rep,packed,name=fail,proto3" json:"fail,omitempty"`
	Warn                 []uint64 `protobuf:"varint,3,rep,packed,name=warn,proto3" json:"warn,omitempty"`
	Del                  []uint64 `protobuf:"varint,4,rep,packed,name=del,proto3" json:"del,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LiveResultRequest) Reset()         { *m = LiveResultRequest{} }
func (m *LiveResultRequest) String() string { return proto.CompactTextString(m) }
func (*LiveResultRequest) ProtoMessage()    {}
func (*LiveResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{21}
}

func (m *LiveResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiveResultRequest.Unmarshal(m, b)
}
func (m *LiveResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiveResultRequest.Marshal(b, m, deterministic)
}
func (m *LiveResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiveResultRequest.Merge(m, src)
}
func (m *LiveResultRequest) XXX_Size() int {
	return xxx_messageInfo_LiveResultRequest.Size(m)
}
func (m *LiveResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LiveResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LiveResultRequest proto.InternalMessageInfo

func (m *LiveResultRequest) GetSuccess() []uint64 {
	if m != nil {
		return m.Success
	}
	return nil
}

func (m *LiveResultRequest) GetFail() []uint64 {
	if m != nil {
		return m.Fail
	}
	return nil
}

func (m *LiveResultRequest) GetWarn() []uint64 {
	if m != nil {
		return m.Warn
	}
	return nil
}

func (m *LiveResultRequest) GetDel() []uint64 {
	if m != nil {
		return m.Del
	}
	return nil
}

type LiveResultReply struct {
	Res                  *CommonReply `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LiveResultReply) Reset()         { *m = LiveResultReply{} }
func (m *LiveResultReply) String() string { return proto.CompactTextString(m) }
func (*LiveResultReply) ProtoMessage()    {}
func (*LiveResultReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{22}
}

func (m *LiveResultReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiveResultReply.Unmarshal(m, b)
}
func (m *LiveResultReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiveResultReply.Marshal(b, m, deterministic)
}
func (m *LiveResultReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiveResultReply.Merge(m, src)
}
func (m *LiveResultReply) XXX_Size() int {
	return xxx_messageInfo_LiveResultReply.Size(m)
}
func (m *LiveResultReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LiveResultReply.DiscardUnknown(m)
}

var xxx_messageInfo_LiveResultReply proto.InternalMessageInfo

func (m *LiveResultReply) GetRes() *CommonReply {
	if m != nil {
		return m.Res
	}
	return nil
}

// 死信消息派发结果，同步和上报使用同一个结构体
type DeadResultRequest struct {
	Success              []uint64     `protobuf:"varint,1,rep,packed,name=success,proto3" json:"success,omitempty"`
	Fail                 []*StorePack `protobuf:"bytes,2,rep,name=fail,proto3" json:"fail,omitempty"`
	Warn                 []uint64     `protobuf:"varint,3,rep,packed,name=warn,proto3" json:"warn,omitempty"`
	Del                  []uint64     `protobuf:"varint,4,rep,packed,name=del,proto3" json:"del,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DeadResultRequest) Reset()         { *m = DeadResultRequest{} }
func (m *DeadResultRequest) String() string { return proto.CompactTextString(m) }
func (*DeadResultRequest) ProtoMessage()    {}
func (*DeadResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{23}
}

func (m *DeadResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeadResultRequest.Unmarshal(m, b)
}
func (m *DeadResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeadResultRequest.Marshal(b, m, deterministic)
}
func (m *DeadResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeadResultRequest.Merge(m, src)
}
func (m *DeadResultRequest) XXX_Size() int {
	return xxx_messageInfo_DeadResultRequest.Size(m)
}
func (m *DeadResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeadResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeadResultRequest proto.InternalMessageInfo

func (m *DeadResultRequest) GetSuccess() []uint64 {
	if m != nil {
		return m.Success
	}
	return nil
}

func (m *DeadResultRequest) GetFail() []*StorePack {
	if m != nil {
		return m.Fail
	}
	return nil
}

func (m *DeadResultRequest) GetWarn() []uint64 {
	if m != nil {
		return m.Warn
	}
	return nil
}

func (m *DeadResultRequest) GetDel() []uint64 {
	if m != nil {
		return m.Del
	}
	return nil
}

type DeadResultReply struct {
	Res                  *CommonReply `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DeadResultReply) Reset()         { *m = DeadResultReply{} }
func (m *DeadResultReply) String() string { return proto.CompactTextString(m) }
func (*DeadResultReply) ProtoMessage()    {}
func (*DeadResultReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e27ef7f6063213, []int{24}
}

func (m *DeadResultReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeadResultReply.Unmarshal(m, b)
}
func (m *DeadResultReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeadResultReply.Marshal(b, m, deterministic)
}
func (m *DeadResultReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeadResultReply.Merge(m, src)
}
func (m *DeadResultReply) XXX_Size() int {
	return xxx_messageInfo_DeadResultReply.Size(m)
}
func (m *DeadResultReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeadResultReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeadResultReply proto.InternalMessageInfo

func (m *DeadResultReply) GetRes() *CommonReply {
	if m != nil {
		return m.Res
	}
	return nil
}

func init() {
	proto.RegisterEnum("iproto.CusCmd", CusCmd_name, CusCmd_value)
	proto.RegisterType((*StorePack)(nil), "iproto.StorePack")
	proto.RegisterMapType((map[string]uint32)(nil), "iproto.StorePack.PeersEntry")
	proto.RegisterType((*ApplyLogEntry)(nil), "iproto.applyLogEntry")
	proto.RegisterType((*CommonReply)(nil), "iproto.CommonReply")
	proto.RegisterType((*RaftApplyRequest)(nil), "iproto.RaftApplyRequest")
	proto.RegisterType((*RaftApplyReply)(nil), "iproto.RaftApplyReply")
	proto.RegisterType((*CollectClusterIndexRequest)(nil), "iproto.CollectClusterIndexRequest")
	proto.RegisterType((*CollectClusterIndexReply)(nil), "iproto.CollectClusterIndexReply")
	proto.RegisterType((*SyncClusterIndexRequest)(nil), "iproto.SyncClusterIndexRequest")
	proto.RegisterType((*SyncClusterIndexReply)(nil), "iproto.SyncClusterIndexReply")
	proto.RegisterType((*SyncSubscribeInfoRequest)(nil), "iproto.SyncSubscribeInfoRequest")
	proto.RegisterMapType((map[uint32]uint32)(nil), "iproto.SyncSubscribeInfoRequest.DataEntry")
	proto.RegisterType((*SyncSubscribeInfoReply)(nil), "iproto.SyncSubscribeInfoReply")
	proto.RegisterType((*SyncSubscribeInfoOffsetRequest)(nil), "iproto.SyncSubscribeInfoOffsetRequest")
	proto.RegisterType((*SyncSubscribeInfoOffsetReply)(nil), "iproto.SyncSubscribeInfoOffsetReply")
	proto.RegisterType((*AskIndexRequest)(nil), "iproto.AskIndexRequest")
	proto.RegisterType((*AskIndexReply)(nil), "iproto.AskIndexReply")
	proto.RegisterType((*AskSubscribedInfoRequest)(nil), "iproto.AskSubscribedInfoRequest")
	proto.RegisterMapType((map[uint32]uint32)(nil), "iproto.AskSubscribedInfoRequest.DataEntry")
	proto.RegisterType((*AskSubscribedInfoReply)(nil), "iproto.AskSubscribedInfoReply")
	proto.RegisterMapType((map[uint32]uint32)(nil), "iproto.AskSubscribedInfoReply.DataEntry")
	proto.RegisterType((*AskIncreasedIndexRequest)(nil), "iproto.AskIncreasedIndexRequest")
	proto.RegisterType((*AskIncreasedIndexReply)(nil), "iproto.AskIncreasedIndexReply")
	proto.RegisterType((*NewMsgRequest)(nil), "iproto.NewMsgRequest")
	proto.RegisterType((*NewMsgReply)(nil), "iproto.NewMsgReply")
	proto.RegisterType((*LiveResultRequest)(nil), "iproto.LiveResultRequest")
	proto.RegisterType((*LiveResultReply)(nil), "iproto.LiveResultReply")
	proto.RegisterType((*DeadResultRequest)(nil), "iproto.DeadResultRequest")
	proto.RegisterType((*DeadResultReply)(nil), "iproto.DeadResultReply")
}

func init() { proto.RegisterFile("clustermsg.proto", fileDescriptor_15e27ef7f6063213) }

var fileDescriptor_15e27ef7f6063213 = []byte{
	// 824 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x51, 0x6f, 0xe3, 0x44,
	0x10, 0xc6, 0xb1, 0x9b, 0x4b, 0x26, 0x71, 0x6e, 0xb3, 0xd7, 0xeb, 0xf9, 0xa2, 0x72, 0x8a, 0x2c,
	0x55, 0x44, 0xf7, 0xe0, 0x4a, 0x39, 0xc4, 0x55, 0x08, 0x15, 0x45, 0x69, 0x1f, 0x2a, 0x95, 0x52,
	0x6d, 0x41, 0x3c, 0x80, 0x90, 0x1c, 0x7b, 0x13, 0x59, 0x71, 0xbc, 0xc1, 0x6b, 0xb7, 0x98, 0xbf,
	0xc1, 0x6f, 0xe0, 0x2f, 0x20, 0xde, 0xf9, 0x63, 0x68, 0x77, 0x63, 0xc7, 0x6d, 0x5c, 0x48, 0x4a,
	0x9f, 0x3c, 0x3b, 0xbb, 0xfb, 0xcd, 0x37, 0x33, 0x9f, 0x67, 0x01, 0x79, 0x61, 0xca, 0x13, 0x1a,
	0x2f, 0xf8, 0xcc, 0x59, 0xc6, 0x2c, 0x61, 0xb8, 0x1e, 0xc8, 0x6f, 0xef, 0xed, 0x8c, 0xb1, 0x59,
	0x48, 0x8f, 0xe5, 0x6a, 0x92, 0x4e, 0x8f, 0xdd, 0x28, 0x53, 0x47, 0xec, 0xbf, 0x35, 0x68, 0xde,
	0x24, 0x2c, 0xa6, 0xd7, 0xae, 0x37, 0xc7, 0xfb, 0xb0, 0x17, 0x44, 0x3e, 0xfd, 0xd5, 0xd2, 0xfa,
	0xda, 0xc0, 0x20, 0x6a, 0x81, 0x87, 0xb0, 0xb7, 0xa4, 0x34, 0xe6, 0x56, 0xad, 0xaf, 0x0f, 0x5a,
	0xc3, 0x43, 0x47, 0xc1, 0x3a, 0xc5, 0x3d, 0xe7, 0x5a, 0x6c, 0x9f, 0x47, 0x49, 0x9c, 0x11, 0x75,
	0x14, 0x63, 0x30, 0x7c, 0x37, 0x71, 0x2d, 0xbd, 0xaf, 0x0d, 0xda, 0x44, 0xda, 0xf8, 0x1d, 0x40,
	0x4c, 0x3d, 0x16, 0xfb, 0xdf, 0x05, 0x0b, 0x6a, 0x19, 0x7d, 0x6d, 0xa0, 0x93, 0x92, 0xa7, 0x77,
	0x02, 0xb0, 0x06, 0xc2, 0x08, 0xf4, 0x39, 0xcd, 0x24, 0x93, 0x26, 0x11, 0xa6, 0x60, 0x77, 0xeb,
	0x86, 0x29, 0xb5, 0x6a, 0x7d, 0x6d, 0x60, 0x12, 0xb5, 0xf8, 0xb2, 0x76, 0xa2, 0xd9, 0x3f, 0x82,
	0xe9, 0x2e, 0x97, 0x61, 0x76, 0xc9, 0x66, 0xea, 0x72, 0x1f, 0x74, 0x6f, 0xe1, 0xcb, 0xcb, 0x9d,
	0x61, 0x27, 0x27, 0x3c, 0x4e, 0xf9, 0x78, 0xe1, 0x13, 0xb1, 0x85, 0x07, 0x2b, 0x82, 0x02, 0xab,
	0x35, 0xdc, 0x77, 0x54, 0x89, 0x9c, 0xbc, 0x44, 0xce, 0x28, 0xca, 0x14, 0x6d, 0xfb, 0x03, 0xb4,
	0xc6, 0x6c, 0xb1, 0x60, 0x11, 0xa1, 0xcb, 0x30, 0x13, 0x99, 0x79, 0xcc, 0xa7, 0x12, 0xdb, 0x24,
	0xd2, 0x16, 0x5c, 0x17, 0x7c, 0x26, 0xb1, 0x9a, 0x44, 0x98, 0xf6, 0xcf, 0x80, 0x88, 0x3b, 0x4d,
	0x46, 0x82, 0x15, 0xa1, 0xbf, 0xa4, 0x94, 0x27, 0xcf, 0x4a, 0xea, 0x23, 0x74, 0x4a, 0xf8, 0x82,
	0xd7, 0x11, 0xe8, 0x31, 0xe5, 0x12, 0xbd, 0x35, 0x7c, 0x55, 0xa0, 0xaf, 0x99, 0x13, 0xb1, 0x6f,
	0x1f, 0x42, 0x6f, 0xcc, 0xc2, 0x90, 0x7a, 0xc9, 0x58, 0xc9, 0xe5, 0x42, 0xf4, 0x78, 0x45, 0xd1,
	0xfe, 0x01, 0xac, 0xca, 0xdd, 0xed, 0x03, 0xac, 0x35, 0xa4, 0x97, 0x34, 0x64, 0x1f, 0xc3, 0x9b,
	0x9b, 0x2c, 0xf2, 0x2a, 0x62, 0x56, 0x8b, 0xce, 0x3e, 0x85, 0xd7, 0x9b, 0x17, 0x76, 0xc8, 0xf3,
	0x77, 0x0d, 0x2c, 0x01, 0x70, 0x93, 0x4e, 0xb8, 0x17, 0x07, 0x13, 0x7a, 0x11, 0x4d, 0x59, 0x1e,
	0xf2, 0x74, 0x55, 0x67, 0x4d, 0x0a, 0xfa, 0x7d, 0x21, 0xe8, 0x47, 0xce, 0x3b, 0x67, 0x6e, 0xe2,
	0x2a, 0x79, 0xcb, 0x7b, 0xbd, 0x8f, 0xd0, 0x2c, 0x5c, 0x65, 0xa1, 0x9a, 0xff, 0x25, 0xd4, 0xaf,
	0xe1, 0xa0, 0x22, 0xc8, 0x0e, 0x69, 0xfd, 0x04, 0xef, 0x36, 0x00, 0xbe, 0x9d, 0x4e, 0x39, 0x4d,
	0xf2, 0xdc, 0x0e, 0xa0, 0xee, 0x7a, 0x49, 0xc0, 0x22, 0x89, 0xd5, 0x20, 0xab, 0x95, 0xa0, 0x19,
	0xf8, 0xea, 0x1f, 0x36, 0x89, 0x30, 0x73, 0xe2, 0x7a, 0xf1, 0x87, 0xd9, 0xe7, 0x70, 0xf8, 0x28,
	0xfa, 0x0e, 0x24, 0x3f, 0x83, 0x97, 0x23, 0x3e, 0xdf, 0xa2, 0xc9, 0x97, 0x60, 0xae, 0x0f, 0x3e,
	0x45, 0x63, 0xb5, 0x32, 0xda, 0x1f, 0x1a, 0x58, 0x23, 0x3e, 0x2f, 0xd8, 0xfb, 0x5b, 0xb4, 0xfc,
	0xb1, 0xf3, 0x0f, 0x5b, 0x2e, 0x8a, 0x35, 0x89, 0x99, 0x0c, 0xd8, 0x20, 0xc2, 0x7c, 0xba, 0x08,
	0xfe, 0xd4, 0xe0, 0xa0, 0x22, 0xee, 0x0e, 0xf9, 0x7f, 0x55, 0xcc, 0x09, 0x91, 0xcc, 0xe0, 0x5f,
	0x92, 0x59, 0x86, 0xd9, 0xf3, 0xa9, 0xb7, 0x27, 0xeb, 0x7b, 0x11, 0x79, 0x31, 0x75, 0xb9, 0x88,
	0x50, 0x9a, 0x1c, 0xdf, 0xcb, 0x9c, 0x1e, 0xee, 0xfd, 0xef, 0x9e, 0x7e, 0x01, 0xe6, 0x15, 0xbd,
	0xfb, 0x86, 0xcf, 0xf2, 0x3e, 0x1e, 0xdd, 0xeb, 0x63, 0x77, 0xe3, 0x2d, 0x5a, 0xcd, 0xc7, 0xcf,
	0xa1, 0x95, 0xdf, 0xdb, 0x41, 0xb8, 0x33, 0xe8, 0x5e, 0x06, 0xb7, 0x94, 0x50, 0x9e, 0x86, 0xc5,
	0x0f, 0x65, 0xc1, 0x0b, 0x9e, 0x7a, 0x1e, 0xe5, 0x5c, 0x06, 0x35, 0x48, 0xbe, 0x14, 0x4f, 0xc1,
	0xd4, 0x0d, 0x42, 0xd9, 0x06, 0x83, 0x48, 0x5b, 0xf8, 0xee, 0xdc, 0x38, 0xb2, 0x74, 0xe5, 0x13,
	0xb6, 0xa8, 0xb1, 0x4f, 0x43, 0xcb, 0x90, 0x2e, 0x61, 0xda, 0x27, 0xf0, 0xb2, 0x1c, 0x68, 0x07,
	0x8a, 0xbf, 0x41, 0xf7, 0x8c, 0xba, 0xfe, 0xb6, 0x14, 0x8f, 0x4a, 0x14, 0xab, 0xcb, 0xb5, 0x1b,
	0xeb, 0x72, 0xec, 0xed, 0x59, 0xbf, 0xff, 0xab, 0x06, 0x75, 0xf5, 0xd0, 0xe1, 0x06, 0x18, 0x57,
	0x2c, 0xa2, 0xe8, 0x13, 0xbc, 0x0f, 0xe8, 0xe1, 0x88, 0x47, 0x1a, 0x7e, 0x0d, 0xdd, 0x8d, 0x19,
	0x84, 0x6a, 0xb8, 0x03, 0x20, 0xdc, 0xaa, 0xa9, 0x48, 0xc7, 0x18, 0x3a, 0x62, 0xbd, 0xae, 0x22,
	0x32, 0x72, 0xdf, 0x9a, 0x23, 0xda, 0xc3, 0x26, 0x34, 0x8b, 0x87, 0x12, 0xd5, 0xf1, 0x1b, 0x78,
	0x55, 0xf1, 0xc0, 0xa1, 0x17, 0xb8, 0x0d, 0x8d, 0x7c, 0x14, 0xa1, 0x86, 0x20, 0xb1, 0xf1, 0x33,
	0xa1, 0xe6, 0xca, 0x7d, 0x5f, 0xe4, 0x08, 0xf0, 0xa7, 0xf0, 0x96, 0xd0, 0x25, 0x8b, 0x93, 0x8a,
	0xc1, 0x89, 0x5a, 0x18, 0x41, 0x5b, 0x6d, 0xaf, 0xc8, 0xb7, 0x45, 0xe6, 0xca, 0x53, 0xa2, 0x6f,
	0xae, 0xbd, 0xa5, 0x04, 0x3a, 0x93, 0xba, 0x2c, 0xe9, 0x87, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xcb, 0x79, 0xb5, 0x61, 0xdf, 0x09, 0x00, 0x00,
}
